name: CI

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up C++ environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake

    - name: Build C++ project
      run: |
        cd InputMethod
        mkdir -p build
        cd build
        cmake ..
        make

    - name: SetupJDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '21'

    - name: Set up Android environment
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        mkdir -p cmdline-tools/latest
        unzip commandlinetools-linux-11076708_latest.zip
        mv cmdline-tools/bin cmdline-tools/latest
        mv cmdline-tools/lib cmdline-tools/latest
        mv cmdline-tools/NOTICE.txt cmdline-tools/latest
        mv cmdline-tools/source.properties cmdline-tools/latest
        java --version
        yes | cmdline-tools/latest/bin/sdkmanager "platforms;android-33" "build-tools;33.0.2" "cmdline-tools;latest"

    - name: Build Android project
      run: |
        cd AndroidApp
        ./gradlew assembleDebug
