name: CI

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up C++ environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake

    - name: Build C++ project
      run: |
        cd InputMethod
        mkdir -p build
        cd build
        cmake ..
        make

    - name: Set up Android environment
      run: |
        sudo apt-get install -y openjdk-21-jdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
        unzip commandlinetools-linux-8512546_latest.zip -d tools
        yes | tools/bin/sdkmanager --sdk_root=${HOME}/android-sdk "platforms;android-30" "build-tools;30.0.3"

    - name: Build Android project
      run: |
        cd AndroidApp
        ./gradlew assembleDebug
