name: CI

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up C++ environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libfcitx5core-dev libfcitx5-qt-dev -q

    - name: Build C++ project
      run: |
        pwd
        cd UDPInput
        mkdir -p build
        cd build
        cmake ..
        make
        cpack
        pwd
    - name: Upload .deb to GitHub Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./UDPInput/build/UDPInput.deb
        asset_name: UDPInput.deb
        asset_content_type: application/octet-stream

    - name: SetupJDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '21'

    - name: Set up Android environment
      run: |
        pwd
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -nv
        mkdir -p cmdline-tools/latest
        unzip commandlinetools-linux-11076708_latest.zip
        mv cmdline-tools/bin cmdline-tools/latest
        mv cmdline-tools/lib cmdline-tools/latest
        mv cmdline-tools/NOTICE.txt cmdline-tools/latest
        mv cmdline-tools/source.properties cmdline-tools/latest
        java --version
        yes | cmdline-tools/latest/bin/sdkmanager "platforms;android-33" "build-tools;33.0.0"
        pwd
    - name: Set up Gradle Wrapper
      run: |
        gradle wrapper --gradle-version 8.9

    - name: Build Android project
      run: |
        ./gradlew assembleDebug
